tcf-agent: Update to current version
While there has not been an official release in some time, the latest version
fixes a large number of bugs and adds support for Dwarf 5, among other
things.  (Dwarf 5 is default in gcc 12 and newer.)

Short change log since the last version:
    TCF Agent: Narrow down LoadLibrary search scope
    TCF Agent: faster breakpoint planting
    Bug 581214 - Expression evaluation fails for a data member that is defined in a structure, union or class that is of type DW_AT_data_bit_offset attribute (DWARF5)
    TCF Agent: reduced memory footprint
    TCF Agent: fixed build error on CygWin: CYGWIN_VERSION_CYGWIN_CONV undefined
    TCF Agent: workaround for GCC compilation error: function may return address of local variable
    Bug 581034 - "long long int" data type can't be recognized from dwarf5 debug info generated by llvm15
    TCF Agent: Removal of unused variable causing clang-15 build error
    TCF Agent: fixed: malformed HTTP request can crash the agent
    TCF Agent: fixed assertion failure in the Breakpoints service
    TCF Agent: GDB Remote Serial Protocol: fixed handling of process ID 0
    Bug 580644 - steps into the function of shared library does not work on PPC
    TCF Agent: add PowerPC 32-bit and big-endian builds in the Dockerfile
    TCF Agent: check glibc version when calling pthread_setname_np()
    Bug 580600 - -Wmisleading-indentation issue for gcc version less than 6.0
    Bug 580489 - failed to handle .debug_rnglists section sometimes
    Bug 580450 - failed to read the full compilation unit tag in dwarf 5 when customized sections
    Bug 580414 - failed to handle debug sections for DWARF 5
    Bug 580326 - Can not display the type of global variable defined in a sharedlib
    Fixed text formatting in Makefile.inc
    Bug 580279 - VERSION grep in agent/Makefile.inc need update for vxWorks
    Bug 580089 - pid2id() failed to get a right id
    TCF Agent: improved comments
    TCF Agent: a few more asserts
    TCF Agent: improved X86 disassembler
    Bug 580002 - [tcf-dev] Speedup compute_reverse_lookup_indices
    Bug 579989 - compile error by vs2008 on windows
    TCF Agent: improved X86 disassembler
    Bug 579947 - NULL pointer caused the tcf-server crashed when load ELF file that compiled by LLVM 14 with dwarf-5
    TCF Agent: fixed Coverity warning
    TCF Agent: fixed Coverity warning
    TCF Agent: new function in HTTP server API: closed() call-back
    Merge "TCF Agent: Fix potential memory/resource leaks"
    TCF Agent: Fix potential memory/resource leaks
    TCF Agent: Fix unsafe strcpy
    TCF Agent: Respect certain ENABLE_* macros
    Bug 579412 - incorrect or missing copyright information
    TCF Agent: Lazy PC initialization
    Bug 579362 - the process IDs should be pid_t instead of UINT32 in waitpid.c and waitpid.h files
    Bug 579378 - update copyright year to 2022
    Bug 579274 - unknown option -Wmisleading-indentation issue for gcc version less than 6.0
    TCF Agent: ARM v8 stack crawl: fixed handling of ERET instruction
    TCF Agent: fixed handling of line info file names when file contains a mix DWARF 5 and DWARF 3
    TCF Tests: fixed incorrect error reports in DWARF reader test
    TCF Agent: disabled bogus warnings misleading-indentation
    TCF Agent: fixed handling of line info file names in DWARF 5
    TCF Agent: Expressions: fixed handling of a static field of a struct stored in a register
    TCF Agent: fixed error when building with c++-11
    TCF Agent: DWARF 5: improved handling of location expressions
    TCF Agent: DWARF reader: fixed regression - "FORM_FLAG expected" error
    TCF Agent: DWARF reader: new object flag DOIF_inlined
    TCF Tests: improved tests of var declarations
    TCF Agent: fixed regression: memory corruption in the symbols proxy
    TCF Agent: fixed issues with handling GCC-11 debug info
    TCF Agent: fixed warning: ISO C90 forbids mixed declarations and code
    TCF Agent: Fix stack frame cleanup on error
    TCF Agent: Add missing parentheses
    Bug 578201 - Sometimes variables show as "N/A - Cannot read target memory. Input/output error"
    Bug 577936 - dprintf not work as expected
    TCF Agent: lazy initialization in rand32()
    TCF Agent: new API function: rand32()
    TCF Agent: fixed possible buffer overflow when calling fscanf()
    Bug 577174 - Sometimes variables show as "N/A - Value of register is unknown in the selected frame"
    Bug 577064 - Union type variables don’t show correctly if based on a register
    TCF Agent: fixed: tmp_vprintf and loc_vprintf can segfault on Linux
    Bug 577001 - DW_AT_high_pc with DW_FORM_udata form not handled
    TCF Agent: fixed pthread_cond_timedwait() on Windows
    TCF Agent: Expressions service: improved error message

(From OE-Core rev: 34a6d0e6b23a42fbec5507ab22a5574ad1d38111)

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@kernel.crashing.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit f475ef04ca169944155cc06c5e294b0da22e32f8)
Signed-off-by: Mark Hatle <mark.hatle@amd.com>